### ISSUE TITLE
Split MotionObservable into multiple files

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-android#10]
MotionObservable.java is getting pretty big; can we split it up into smaller files?

**Comment by pingpongboss** [comment]
Would it help if I moved all the Operation types into a separate file?

**Comment by jverkoey** [comment]
I'd expect there to be one class per file. Is this not typically how classes are split up in Java? I'm surprised to see such a large file.

**Comment by pingpongboss** [comment]
🎊 My diff is ready for review at http://codereview.cc/D2997
