### ISSUE TITLE
Should GestureSource.from(gesture) be new GestureSource(gesture)?

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-android#12]
Context: http://codereview.cc/D2247#45260

**Comment by jverkoey** [comment]
My assumption is that visual closeness of APIs will provide more value across platforms than implementation closeness for L2 authors.

**Comment by jverkoey** [comment]
The static method approach might also imply that we can/will add other functionality to the GestureSource type, which would be further deviant from the spec/other platforms.

**Comment by pingpongboss** [comment]
That argument is sound.

One issue which I consider to be a blocker is that `new GestureSource(gesture)` must necessarily return an instance of `GestureSource` which itself extends from `MotionObservable<Gesture>`. The problem is in the naming and will definitely cause confusion for callers who expect to get an Observable back.

**Comment by jverkoey** [comment]
Is this a concern if source is clearly documented as being an observable? Note that this argument holds for swift and js as well.

**Comment by pingpongboss** [comment]
If you view this from the POV of a client who's creating an observable stream, I think it's quite unsettling to be getting a GestureSource back. I do think it'll be a problem for swift/js as well.

I think i should mention this: On Java, I can also name my function gestureSource() as a static function, similar to how you do in swift. The reason why I didn't do that is because by default, the IDE suggests `GestureSource.gestureSource()`. This is unlike swift. The caller can then manually import gestureSource() itself to get rid of the long prefix. If this is what you want me to do, I can do so.

So if the callers do the manual import, then the java code will be 100% visually identical to swift. But I felt that most callers would not bother with the manual import, so their code will look ugly with the prefix. That's when I arrived at the `GestureSource.from()` syntax. This syntax assumes that callers will not manually import `from()` (which would actually be quite ugly), so it makes the worst case scenario better.

**Comment by jverkoey** [comment]
Forking for meta-discussion of Source: https://github.com/material-motion/starmap/issues/108

**Comment by jverkoey** [comment]
Let's go with `GestureSource.from(gesture)` for java. I'll update starmap.

**Comment by jverkoey** [comment]
Added java version of example to https://material-motion.github.io/material-motion/starmap/specifications/streams/sources/gestureSource and https://material-motion.github.io/material-motion/starmap/specifications/streams/sources/springSource
