### ISSUE TITLE
[Messenger sticker editor](https://github.com/material-motion/material-motion/issues/62)

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-android#31]
![](https://cloud.githubusercontent.com/assets/45670/21658585/316bfda6-d295-11e6-8070-41153d659b6b.gif)

**Comment by pingpongboss** [comment]
- [x] Ensure gesture source stream can be written to a view's translation/scale/rotation. May need to keep extra state or logic, maybe in an operator?

- [x] Create directly manipulable interaction that uses a gesture source to write to a view's translation/scale/rotation. 

- [x] Apply interaction to a view target in the main activity

**Comment by jverkoey** [comment]
![sticker0](https://cloud.githubusercontent.com/assets/45670/22528769/b3167192-e8a2-11e6-9b59-b4aa36322e63.png)
![sticker1](https://cloud.githubusercontent.com/assets/45670/22528771/b569c4a8-e8a2-11e6-9744-7686c5ec1d78.png)
![sticker2](https://cloud.githubusercontent.com/assets/45670/22528774/b6e19612-e8a2-11e6-821b-5799beead18c.png)
