### ISSUE TITLE
Implement rewrite/rewriteRange/rewriteTo operators

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-android#61]
https://material-motion.github.io/material-motion/starmap/specifications/operators/rewrite
https://material-motion.github.io/material-motion/starmap/specifications/operators/rewriteRange
https://material-motion.github.io/material-motion/starmap/specifications/operators/rewriteTo

**Comment by pingpongboss** [comment]
🎊 My diff is ready for review at http://codereview.cc/D3018
